/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as StatusSlugRouteImport } from './routes/status.$slug'
import { Route as DashboardStatusPagesRouteImport } from './routes/_dashboard.status-pages'
import { Route as DashboardMonitorsRouteImport } from './routes/_dashboard.monitors'
import { Route as DashboardIncidentsRouteImport } from './routes/_dashboard.incidents'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard.billing'
import { Route as DashboardAlertChannelsRouteImport } from './routes/_dashboard.alert-channels'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as DashboardStatusPagesIdRouteImport } from './routes/_dashboard.status-pages.$id'
import { Route as DashboardMonitorsNewRouteImport } from './routes/_dashboard.monitors.new'
import { Route as DashboardMonitorsIdRouteImport } from './routes/_dashboard.monitors.$id'
import { Route as DashboardIncidentsIdRouteImport } from './routes/_dashboard.incidents.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStatusPagesRoute = DashboardStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitorsRoute = DashboardMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIncidentsRoute = DashboardIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertChannelsRoute = DashboardAlertChannelsRouteImport.update({
  id: '/alert-channels',
  path: '/alert-channels',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardStatusPagesIdRoute = DashboardStatusPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardStatusPagesRoute,
} as any)
const DashboardMonitorsNewRoute = DashboardMonitorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardMonitorsRoute,
} as any)
const DashboardMonitorsIdRoute = DashboardMonitorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardMonitorsRoute,
} as any)
const DashboardIncidentsIdRoute = DashboardIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardIncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/alert-channels': typeof DashboardAlertChannelsRoute
  '/billing': typeof DashboardBillingRoute
  '/incidents': typeof DashboardIncidentsRouteWithChildren
  '/monitors': typeof DashboardMonitorsRouteWithChildren
  '/status-pages': typeof DashboardStatusPagesRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/incidents/$id': typeof DashboardIncidentsIdRoute
  '/monitors/$id': typeof DashboardMonitorsIdRoute
  '/monitors/new': typeof DashboardMonitorsNewRoute
  '/status-pages/$id': typeof DashboardStatusPagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/alert-channels': typeof DashboardAlertChannelsRoute
  '/billing': typeof DashboardBillingRoute
  '/incidents': typeof DashboardIncidentsRouteWithChildren
  '/monitors': typeof DashboardMonitorsRouteWithChildren
  '/status-pages': typeof DashboardStatusPagesRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/incidents/$id': typeof DashboardIncidentsIdRoute
  '/monitors/$id': typeof DashboardMonitorsIdRoute
  '/monitors/new': typeof DashboardMonitorsNewRoute
  '/status-pages/$id': typeof DashboardStatusPagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/alert-channels': typeof DashboardAlertChannelsRoute
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/incidents': typeof DashboardIncidentsRouteWithChildren
  '/_dashboard/monitors': typeof DashboardMonitorsRouteWithChildren
  '/_dashboard/status-pages': typeof DashboardStatusPagesRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/incidents/$id': typeof DashboardIncidentsIdRoute
  '/_dashboard/monitors/$id': typeof DashboardMonitorsIdRoute
  '/_dashboard/monitors/new': typeof DashboardMonitorsNewRoute
  '/_dashboard/status-pages/$id': typeof DashboardStatusPagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/alert-channels'
    | '/billing'
    | '/incidents'
    | '/monitors'
    | '/status-pages'
    | '/status/$slug'
    | '/incidents/$id'
    | '/monitors/$id'
    | '/monitors/new'
    | '/status-pages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/alert-channels'
    | '/billing'
    | '/incidents'
    | '/monitors'
    | '/status-pages'
    | '/status/$slug'
    | '/incidents/$id'
    | '/monitors/$id'
    | '/monitors/new'
    | '/status-pages/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/alert-channels'
    | '/_dashboard/billing'
    | '/_dashboard/incidents'
    | '/_dashboard/monitors'
    | '/_dashboard/status-pages'
    | '/status/$slug'
    | '/_dashboard/'
    | '/_dashboard/incidents/$id'
    | '/_dashboard/monitors/$id'
    | '/_dashboard/monitors/new'
    | '/_dashboard/status-pages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  StatusSlugRoute: typeof StatusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/status-pages': {
      id: '/_dashboard/status-pages'
      path: '/status-pages'
      fullPath: '/status-pages'
      preLoaderRoute: typeof DashboardStatusPagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/monitors': {
      id: '/_dashboard/monitors'
      path: '/monitors'
      fullPath: '/monitors'
      preLoaderRoute: typeof DashboardMonitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/incidents': {
      id: '/_dashboard/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof DashboardIncidentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alert-channels': {
      id: '/_dashboard/alert-channels'
      path: '/alert-channels'
      fullPath: '/alert-channels'
      preLoaderRoute: typeof DashboardAlertChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/status-pages/$id': {
      id: '/_dashboard/status-pages/$id'
      path: '/$id'
      fullPath: '/status-pages/$id'
      preLoaderRoute: typeof DashboardStatusPagesIdRouteImport
      parentRoute: typeof DashboardStatusPagesRoute
    }
    '/_dashboard/monitors/new': {
      id: '/_dashboard/monitors/new'
      path: '/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof DashboardMonitorsNewRouteImport
      parentRoute: typeof DashboardMonitorsRoute
    }
    '/_dashboard/monitors/$id': {
      id: '/_dashboard/monitors/$id'
      path: '/$id'
      fullPath: '/monitors/$id'
      preLoaderRoute: typeof DashboardMonitorsIdRouteImport
      parentRoute: typeof DashboardMonitorsRoute
    }
    '/_dashboard/incidents/$id': {
      id: '/_dashboard/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof DashboardIncidentsIdRouteImport
      parentRoute: typeof DashboardIncidentsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardIncidentsRouteChildren {
  DashboardIncidentsIdRoute: typeof DashboardIncidentsIdRoute
}

const DashboardIncidentsRouteChildren: DashboardIncidentsRouteChildren = {
  DashboardIncidentsIdRoute: DashboardIncidentsIdRoute,
}

const DashboardIncidentsRouteWithChildren =
  DashboardIncidentsRoute._addFileChildren(DashboardIncidentsRouteChildren)

interface DashboardMonitorsRouteChildren {
  DashboardMonitorsIdRoute: typeof DashboardMonitorsIdRoute
  DashboardMonitorsNewRoute: typeof DashboardMonitorsNewRoute
}

const DashboardMonitorsRouteChildren: DashboardMonitorsRouteChildren = {
  DashboardMonitorsIdRoute: DashboardMonitorsIdRoute,
  DashboardMonitorsNewRoute: DashboardMonitorsNewRoute,
}

const DashboardMonitorsRouteWithChildren =
  DashboardMonitorsRoute._addFileChildren(DashboardMonitorsRouteChildren)

interface DashboardStatusPagesRouteChildren {
  DashboardStatusPagesIdRoute: typeof DashboardStatusPagesIdRoute
}

const DashboardStatusPagesRouteChildren: DashboardStatusPagesRouteChildren = {
  DashboardStatusPagesIdRoute: DashboardStatusPagesIdRoute,
}

const DashboardStatusPagesRouteWithChildren =
  DashboardStatusPagesRoute._addFileChildren(DashboardStatusPagesRouteChildren)

interface DashboardRouteChildren {
  DashboardAlertChannelsRoute: typeof DashboardAlertChannelsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardIncidentsRoute: typeof DashboardIncidentsRouteWithChildren
  DashboardMonitorsRoute: typeof DashboardMonitorsRouteWithChildren
  DashboardStatusPagesRoute: typeof DashboardStatusPagesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertChannelsRoute: DashboardAlertChannelsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardIncidentsRoute: DashboardIncidentsRouteWithChildren,
  DashboardMonitorsRoute: DashboardMonitorsRouteWithChildren,
  DashboardStatusPagesRoute: DashboardStatusPagesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  StatusSlugRoute: StatusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
